### ISSUE TITLE
New bug of remodeled switch 5.0.2

### ISSUE THREAD

**Issue by Feles513** [Jan4V/hekate-ipl-50x#12]
After remodeling the right joycon with switch 5.0.2, after the hekate-ipl sent and HBL became bootable, the operation stopped when the left joycon started the game.
But it was usable when removed from the body.
I tried various causes, but it seems to have been caused by a remodeled right joicon.
Using the unmodified right joicon, I was able to use the left joicon.

Is there a way to solve this problem?

**Comment by substanc3-dev** [comment]
Connecting pin 10 on joycon to ground permanently causes the joycon to stop communicating over UART. This causes it to not work when attached to the console. Use a jig for booting instead of a joycon mod to fix this issue.
