### ISSUE TITLE
Copied apps does not show up in HB menu

### ISSUE THREAD

**Issue by eqwoot** [Jan4V/hekate-ipl-50x#13]
I have copied checkpoint to the sd\switch directory root and also tried to copy the checkpoint.nro to the sd root both didn’t show up on hb menu

**Comment by eqwoot** [comment]
fw 5.0.2

**Comment by swoozi** [comment]
place it in switch

**Comment by ZachySwag** [comment]
**Back up all your sd card files before doing this because the data will be lost doing this**

It's simple backup the files and format it into FAT32 format. Your SD card cluster size is probably not 32kb. So just format it to FAT32. Then put all of the backed up files back onto the sd card and you're good.

**Comment by eqwoot** [comment]
Thanks, the problem was solved.  Using Mac to create the folder switch caused the problem.

**Comment by iraizo** [comment]
how did you fixed it im on mac too

**Comment by eqwoot** [comment]
I didn’t bother to fix it, I just replace the hbmenu.  Make sure you delete the switch folder too. 
However I believe if you chmod 777 the switch folder it will work

**Comment by iraizo** [comment]
tell me exactly what i need to do

**Comment by iraizo** [comment]
i fixed it thank god youre my hero <33

**Comment by aadriance** [comment]
what was the fix Shadowcode? chmod or reformat?

**Comment by iraizo** [comment]
chmod your switch folder @aadriance

**Comment by CTCaer** [comment]
FAT32/exFAT do not have permissions.
They are already 0777. I don't understand how this works. It resets the msdos attributes?

Anyway, the real solution is to disable the "windows archive bit" on all folders and files.

Switch's FS has a bug, that rejects files with this bit enabled.

In windows, right click the folder, advanced, untick **Folder/File is ready for archiving**.
In linux, you can do it through mtools' **mattrib -a filename**.
I don't know in mac osx though, but you can probably use the mtools also.

**Comment by iraizo** [comment]
well it worked chmodding it

**Comment by sjogro** [comment]
Thanks for the insight @CTCaer, I used Hekate's archive bit fix and it fixed 2 instances and then worked.
