### ISSUE TITLE
could not launch hekate_ipl.ini

### ISSUE THREAD

**Issue by 9efueifu** [Jan4V/hekate-ipl-50x#16]
does anybody know how to fix this please because when I first tried the method it said failed to mount sd card then i made it bootable with the payload in the hack and when I launched it it said could not launch hekate_ipl.ini then I formated the sd card and just put the sd files on it but it still said could not launch hekate_ipl.ini if anybody knows why this happens and how to fix it please tell me.

**Comment by dezsullivan** [comment]
Hi,

Please make sure that you have placed the files in the correct location. This tutorial is very helpful. 

https://www.youtube.com/watch?v=cHSM8t_7Pco

Regards,

DSullivan

**Comment by 9efueifu** [comment]
I watched the tutorial that you sent me and im getting the same error message and I have hekate_ipl.ini on the sd card so I do not understand why its saying that it can not find that file.
the sd files are copied to the root of the sd card and I using the TegraRcmSmash method to load the payload but it still said the same thing. Im I suppose to have a certain sd card for this to work, I have a 1gb sandisk micro sd card and the switch reads the sd card perfectly fine so is there a problem with sandisk sd cards running homebrew on the nintendo switch

**Comment by 9efueifu** [comment]
I tried the tutorial again and this time its saying unable to mount SD card (please make sure its inserted)

**Comment by reavejr** [comment]
Hello, What is the size of the usb card you are using? If they are to small it will not mount. I was using one from my older phone that was 512megs and had the same issue. Bought a Lexar SDXC 64gb confirmed working on 5.0.2.

**Comment by substanc3-dev** [comment]
The release has been updated with the latest build of mainline hekate, which now supports most SD cards.
