### ISSUE TITLE
5.1.0 support

### ISSUE THREAD

**Issue by Hellacia** [Jan4V/hekate-ipl-50x#20]
Can we have support for 5.1.0

**Comment by hairlessvon** [comment]
I'm sooooo hurt. MY DAUghter updated me on 5.1.0 when she tried to play Mario odyssey. I had everything going. Pfba, megadrive,sums,pic engine etc. now it's gone please get this situated. Please asap please..........

**Comment by ghost** [comment]
guys don't worry there is a patch for it that SciresM posted on his twitter

**Comment by substanc3-dev** [comment]
Release has been updated to support 5.1.0.
