### ISSUE TITLE
Switch turns off after unplugging USB cable

### ISSUE THREAD

**Issue by goop32** [Jan4V/hekate-ipl-50x#4]
Hello!
Booting into CFW/stock worked, but as soon as I'd unplug the USB cable, it would shut off. Have you run across any sort of issues like this or do you think this could be an isolated thing?

Thanks for your hard work!

**Comment by esmith13** [comment]
had this same issue on my switch
on 5.0.2 if it matters

**Comment by Arch9SK7** [comment]
I believe this might be isolated as well... im using this bootloader on two of my switches and neither turn off . Ive unplugged the second it shows the "Nintendo Switch" logo after choosing cfw and anything after that so im not too sure.

**Comment by reavejr** [comment]
Is it the sleep bug?

**Comment by goop32** [comment]
Nah. I'd say from the time I boot Hekate to maybe 3 minutes after, I can't
unplug the USB cable or it'll just shut off.

**Comment by substanc3-dev** [comment]
This is most likely caused by the linux battery issue. Not related to this project.
