### ISSUE TITLE
Dump eMMC BOOT Fail

### ISSUE THREAD

**Issue by iamapie13** [Jan4V/hekate-ipl-50x#5]
I can't dump anything, it tells me to make sure my SD is incerted which it is

**Comment by iamapie13** [comment]
in fact I can't even boot CFW, I can't do anything, it doesn't detect my sd card

**Comment by Breadleyg** [comment]
It seems some people are having trouble getting exFAT formatted SD cards to work.
Perhaps you are having the same issue, check if formatting the SD card to FAT works for you ?

**Comment by iamapie13** [comment]
my micro SD was already in FAT 32, y formatted it again anyways but still not working

**Comment by Arch9SK7** [comment]
I had the same issue once i just simply pulled the card and redid the process. but some people are having exfat issues. but just format SD into fat32 there is a nifty tool online called guiformat to do it for you and you do not lose allocation space.

**Comment by iamapie13** [comment]
i've redone the process countless times, also my sd is not exfat, it's fat32

**Comment by iamapie13** [comment]
I looked for one of my old 4GB micro SD's also in Fat32 (this one I used on my old PSP) also doesn't work

**Comment by Breadleyg** [comment]
Take a look at [this](https://gbatemp.net/threads/anyone-else-having-issues-with-hekate-and-sd-cards.503872/) thread over at gbatemp. Perhaps something in there works for you

**Comment by iamapie13** [comment]
no, mine just simply doesn't work with any sd card, no matter if its been formatted or not

**Comment by substanc3-dev** [comment]
Fixed.
