### ISSUE TITLE
exFAT SD card support?

### ISSUE THREAD

**Issue by x43x61x69** [Jan4V/hekate-ipl-50x#6]
The hbmenu started w/o problem on my 5.0.2 machine. However, I noticed that it couldn't read the NROs from the `/switch` on a 128GB exFAT card but no problem doing the same on a 4GB FAT card.

As I saw somewhere, there's a hekate fork says add exFAT support, I was wondering if the above issue was due to the fact that this build does not have related code to support exFAT cards?

EDIT:

Seems you already enabled exFAT in the `ipl/ffconf.h`. Strange. :(

**Comment by Shinygati** [comment]
Same issue here, can't use sd card if its been formatted by the switch but Fat32 works just fine.

**Comment by Arch9SK7** [comment]
This might be an isolated case because ive tested all my 8, 64, 128 and 256gb cards and all work fine on my switch and along with the bootloader.

**Comment by mistercapitale** [comment]
Ive got the same issue. Everything is setup right, HBmenu 2.0 is working it just doesn't see anything in the directory.

**Comment by aadriance** [comment]
Ran into a similar probably when attempting to back up saves.  Here are the details to try and help nail this down:

- I am using a mac

- SD Card is a 200GB SanDisk Ultra

- Attempted to format in FAT32 from a computer, didn't work

- Attempted to format in exFat from a computer, didn't work

- Attempted to format from a switch, didn't work

Maybe there is a common thread between all our issues?

**Comment by GhostlyCrowd** [comment]
launch ftpd instead of hbm from the albums icon, connect to your switch and delete the switch directory on sd and remake it. xfer your files via ftpd and it will work. i had to do the same thing. for some reason the  switch saw thes witch dir i made as a 0 byte file.

**Comment by x43x61x69** [comment]
I can confirm that @GhostlyCrowd's suggestion DOES WORK.

Even the ftpd was working correctly. It's interesting that when the ftpd loaded this way, it thinks those folders created by macOS as files, not folders.

**Comment by GhostlyCrowd** [comment]
In my case windows 10 created the folder in a way that the switch saw it as a 0byte file and not a directory.  alternatively using gparted to format the sd in fat32 and making the switch directory works every time. it's weird.

**Comment by aadriance** [comment]
Sorry, but how did you make it launch ftpd?  I couldn't find any documentation on that, and simply replacing the hbmenu.nro didn't work

**Comment by x43x61x69** [comment]
If it didn’t work, you are doing it wrong.

**Comment by GhostlyCrowd** [comment]
replacing   hbmenu.nro with ftpd.nro renamed to  hbmenu.nro works.

**Comment by aadriance** [comment]
ah, I hadn't thought to rename it, silly me :)

**Comment by mistercapitale** [comment]
I can concur, @GhostlyCrowd solution worked flawlessly. THANK YOU!!!!

**Comment by substanc3-dev** [comment]
Fixed.
