### ISSUE TITLE
Cfw freeze at sleep mode

### ISSUE THREAD

**Issue by cad1112** [Jan4V/hekate-ipl-50x#7]
When you put switch in sleep mode it freeze and won’t power up again

**Comment by chronoss09** [comment]
I have the same problem, hold down **Volume-** and **Power** during **10s** to shutdown your Switch !

**Comment by Arch9SK7** [comment]
The bootloader is still experimental no one has this working yet.

**Comment by Marioaddict3** [comment]
Same issue, would be a nice fix

**Comment by substanc3-dev** [comment]
Fixed.
