### ISSUE TITLE
Regular software will not start after opening hbl (5.0.2)

### ISSUE THREAD

**Issue by jpxdude** [Jan4V/hekate-ipl-50x#9]
After running hbl then exiting with home button, opening any normal games (either downloaded or from a game card) freezes on black loading screen with spinning NSW logo in bottom left.  Can exit with home button, but nothing works until reboot.

**Comment by Arch9SK7** [comment]
This is because it is only a mere bootloader of the cfw it's not complete so of course games do not run yet. SciresM himself only just got it working for himself. So this issue is unneeded.

**Comment by Arch9SK7** [comment]
@Jan4V  Wanna close this?

**Comment by jpxdude** [comment]
Hi thanks for the reply!  I was only wondering if this was normal behaviour for now, as games work before opening hbl once booted into cfw.  They just stop working immediately after using hbl and going home.

**Comment by substanc3-dev** [comment]
Fixed in latest release.
